baseURL: "http://example.org/"
languageCode: "en-us"
title: "My New Hugo Site"
theme: "blank"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: 10
  - name: About Us
    url: /about/
    weight: 20
  - name: Service
    url: /service/
    weight: 30
  - name: Blog
    title: Blog
    url: /blog/
    weight: 40
  - name: Contact
    url: /contact/
    weight: 50
